name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/cloud-go-app:latest -f docker/Dockerfile .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/cloud-go-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
          
            docker stop cloud-api || true
            docker rm cloud-api || true
            docker network create app-net || true
            docker pull naqua/cloud-go-app:latest

            docker run -d \
              --name postgres \
              --network app-net \
              -e POSTGRES_USER=postgres \
              -e POSTGRES_PASSWORD=postgres \
              -e POSTGRES_DB=appdb \
               postgres:16
            
            sleep 10

            docker run -d \
             --name cloud-api \
             --network app-net \
             -p 8081:8081 \
             -e DB_CONN="postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable" \
            naqua/cloud-go-app:latest
           
